name: Scala CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  job_id:
    # ...

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      # actions/checkout MUST come before auth
      - uses: actions/checkout@v3

      - id: 'auth'
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: 'projects/461060249876/locations/global/workloadIdentityPools/gh-action-pool/providers/gh-action-provider'
          service_account: 'github-action-authentication@data-projects-322512.iam.gserviceaccount.com'

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'
      - name: Run tests
        env:
          GITHUB_TOKEN: ${{ secrets.RUNNER }}
        run: sbt coverage test
      - name: Coverage Report
        run: sbt coverageReport
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3

